// TODO: setup PrimaryColor
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    colors: {
      transparent: "transparent",
      white: "#FFFFFF",
      black: "#000000",
      primary: {
        50: process.env.TAILWIND_PRIMARY_COLOR_50,
        100: process.env.TAILWIND_PRIMARY_COLOR_100,
        200: process.env.TAILWIND_PRIMARY_COLOR_200,
        300: process.env.TAILWIND_PRIMARY_COLOR_300,
        400: process.env.TAILWIND_PRIMARY_COLOR_400,
        500: process.env.TAILWIND_PRIMARY_COLOR_500,
        600: process.env.TAILWIND_PRIMARY_COLOR_600,
        700: process.env.TAILWIND_PRIMARY_COLOR_700,
        800: process.env.TAILWIND_PRIMARY_COLOR_800,
        900: process.env.TAILWIND_PRIMARY_COLOR_900,
      },
      gray: {
        50: "#fcfcfc",
        100: "#f7f7f7",
        200: "#ebebeb",
        300: "#dbdbdb",
        400: "#b3b3b3",
        500: "#808080",
        600: "#636363",
        700: "#525252",
        800: "#404040",
        900: "#2e2e2e",
      },
    },
    fontFamily: {
      sans: [
        "-apple-system",
        "Noto Sans",
        "Helvetica Neue",
        "Helvetica",
        "Nimbus Sans L",
        "Arial",
        "Liberation Sans",
        "PingFang TC",
        "Hiragino Sans CNS",
        "Noto Sans CJK TC",
        "Source Han Sans TC",
        "Source Han Sans CN",
        "Microsoft JhengHei",
        "Wenquanyi Micro Hei",
        "WenQuanYi Zen Hei",
        "Heiti TC",
        "SimHei",
        "WenQuanYi Zen Hei Sharp",
        "sans-serif",
      ],
    },
  },
  variants: {},
  plugins: [require("@tailwindcss/line-clamp")],
}
